if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#default config
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(git zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh
export EDITOR=vim
set -o vi

# zsh-autosuggestions 
HISTFILE=~/.zsh_history
HISTSIZE=500000
SAVEHIST=500000
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

#go 
#export PATH=$PATH:$HOME/go/bin
export PATH=$PATH:/usr/local/bin/mockery
export GO111MODULE=on
export GOPATH=~/go
########export GOROOT=/usr/local/go
unset GOROOT
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
export GOTOOLCHAIN=local

#docker 
export DOCKER_API_VERSION=1.44
#alias
alias py='python3'
alias bazel='bazelisk'
alias charm'pycharm'
# k8s
alias ktl='kubectl'
alias k='kubectl'
alias kg='k get'
alias kgp='kg pod'
alias kgd='kg deployment'
alias kgs='kg services'
alias kgr='kg replicaset'
alias ka='k apply'
alias kdel='k delete'
alias kdes='k describe'
alias kctx='kubectx'
alias kns='kubens'

alias kn='f() { [ "$1" ] && kubectl config set-context --current --namespace $1 || kubectl config view --minify | grep namespace | cut -d" " -f6 ; } ; f'
export kdo='--dry-run=client -o yaml'
export know='--force --grace-period=0'
# terraform
alias tf='terraform'

#app 
export PATH=$PATH:$HOME/apps/idea/bin

#neovim
export PATH="$PATH:/opt/nvim-linux-x86_64/bin"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

alias wt='~/workspace/tekone.wt/wt'
wtcd() { cd "$(wt path "$1")"; }

alias claude-rr="~/workspace/claude-rr/claude-rr.sh"
alias claude-usage="python3 ~/workspace/claude-rr/claude-usage.py"


eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="$HOME/.local/bin:$PATH"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
